variables:
  APP: 'browser-sdk'
  CURRENT_CI_IMAGE: 12
  BUILD_STABLE_REGISTRY: '486234852809.dkr.ecr.us-east-1.amazonaws.com'
  CI_IMAGE: '$BUILD_STABLE_REGISTRY/ci/$APP:$CURRENT_CI_IMAGE'

stages:
  - ci-image
  - pre-publish
  - publish

pre-publish:
  stage: pre-publish
  tags: ['runner:main', 'size:large']
  image: $CI_IMAGE
  artifacts:
    paths:
      - build/
  script:
    - mkdir build
    - echo coucou > build/coucou.txt

publish:
  stage: publish
  tags: ['runner:main', 'size:large']
  image: $CI_IMAGE
  dependencies:
    - pre-publish
  script:
    - cat build/coucou.txt

ci-image:
  stage: ci-image
  when: manual
  except: [tags, schedules]
  tags: ['runner:docker', 'size:large']
  image: $BUILD_STABLE_REGISTRY/docker:18.03.1
  script:
    - docker build --tag $CI_IMAGE .
    - docker push $CI_IMAGE
